services:
  book-reviews:
    build: .
    ports: 
      - "8000:8000"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    
  postgres:
    image: postgres:18.3-alpine
    volumes:
      - ./bookdb:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bookdb" ]
      interval: 5s
      timeout: 3s
      retries: 3